# Generated by Django 3.2.7 on 2021-11-03 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('photo', models.ImageField(default='default_avatar/student_avatar1.png', upload_to='user_photo/student/', verbose_name='Photo')),
                ('resume', models.FileField(default='default_resume/no_resume.png', upload_to='user_resume/student/', verbose_name='Resume')),
                ('previous_educational_institution', models.CharField(default='-', max_length=100, null=True, verbose_name='Previous educational institution')),
                ('invited', models.IntegerField(default=0, verbose_name='Number of invited students')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
            bases=('users.user',),
        ),
    ]
