# Generated by Django 3.2.7 on 2021-11-02 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211102_1736'),
        ('students', '0002_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='default_avatar/student_avatar2.png', upload_to='user_photo/student/', verbose_name='Photo'),
        ),
    ]
