# Generated by Django 3.2.7 on 2021-11-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20211102_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='default_avatar/student_avatar5.png', upload_to='user_photo/student/', verbose_name='Photo'),
        ),
    ]
