# Generated by Django 3.2.7 on 2021-11-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0013_auto_20211103_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='City')),
                ('birthday', models.DateField(null=True, verbose_name='Birthday')),
                ('phone_number', models.CharField(max_length=50, null=True, unique=True, verbose_name='Phone number')),
                ('faculty', models.CharField(default='not chosen', max_length=255, verbose_name='Faculty')),
                ('position', models.CharField(default='not chosen', max_length=255, verbose_name='Position')),
                ('filled', models.BooleanField(default=False, verbose_name='Filled information status')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
