# Generated by Django 3.2.7 on 2021-10-21 12:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='previous_educational_institution',
            field=models.CharField(default='-', max_length=100, null=True, verbose_name='Previous educational institution'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(to='users.Course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_of_employment',
            field=models.DateField(default=datetime.datetime.now, null=True, verbose_name='Date of employment'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience_in_years',
            field=models.IntegerField(default=0, null=True, verbose_name='Experience in years'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='faculty',
            field=models.CharField(default='not chosen', max_length=255, verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(default='not chosen', max_length=255, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time of creation'),
        ),
    ]
