# Generated by Django 3.2.7 on 2021-10-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='/static/users/images/default_avatar.png', upload_to='photos/%Y/%m/%d/', verbose_name='Photo'),
        ),
    ]
