# Generated by Django 3.2.7 on 2021-11-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211102_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='time_create',
        ),
    ]
