# Generated by Django 3.2.7 on 2021-10-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='default_avatar/student_avatar8.png', upload_to='user_photo/student/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(default='default_avatar/teacher_avatar.png', upload_to='user_photo/teacher/', verbose_name='Photo'),
        ),
    ]
