# Generated by Django 3.2.7 on 2021-10-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211023_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='resume',
            field=models.FileField(null=True, upload_to='user_resume/student/', verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='default_avatar/student_avatar15.png', upload_to='user_photo/student/', verbose_name='Photo'),
        ),
    ]
