# Generated by Django 3.2.7 on 2021-10-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211023_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='default_avatar/student_avatar9.png', upload_to='user_photo/student/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(default='Not included', null=True, upload_to='user_resume/student/', verbose_name='Resume'),
        ),
    ]
