# Generated by Django 3.2.7 on 2021-10-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20211023_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='invited',
            field=models.IntegerField(default=0, verbose_name='Number of invited students'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='default_avatar/student_avatar3.png', upload_to='user_photo/student/', verbose_name='Photo'),
        ),
    ]
