# Generated by Django 3.2.7 on 2021-10-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('faculty', models.CharField(max_length=30)),
                ('course', models.IntegerField(default=1, null=True)),
                ('headman', models.CharField(default='-', max_length=50, null=True)),
                ('photo', models.ImageField(default='-', null=True, upload_to='photos/%Y/%m/%d/')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
